import type { Notification } from "@/types/notification"

export const mockNotifications: Notification[] = [
  {
    id: "1",
    title: "Новая заявка",
    message: "Поступила новая заявка от Иванова А.С.",
    type: "info",
    read: false,
    createdAt: "2 минуты назад",
    href: "/applications/1",
  },
  {
    id: "2",
    title: "Документ подписан",
    message: "Документ 'Соглашение о сотрудничестве' успешно подписан",
    type: "success",
    read: false,
    createdAt: "15 минут назад",
    href: "/documents/5",
  },
  {
    id: "3",
    title: "Соревнование завершено",
    message: "Соревнование 'Первенство России U-18' завершено",
    type: "info",
    read: true,
    createdAt: "1 час назад",
    href: "/competitions/001",
  },
  {
    id: "4",
    title: "Требуется внимание",
    message: "Заявка от Петрова В.И. ожидает рассмотрения более 3 дней",
    type: "warning",
    read: false,
    createdAt: "2 часа назад",
    href: "/applications/3",
  },
  {
    id: "5",
    title: "Новый пользователь",
    message: "Зарегистрирован новый пользователь: Сидорова М.А.",
    type: "info",
    read: true,
    createdAt: "3 часа назад",
    href: "/users/15",
  },
  {
    id: "6",
    title: "Ошибка подписания",
    message: "Не удалось подписать документ 'Договор аренды'",
    type: "error",
    read: false,
    createdAt: "5 часов назад",
    href: "/documents/8",
  },
  {
    id: "7",
    title: "Заявка одобрена",
    message: "Заявка от Смирнова А.В. была одобрена",
    type: "success",
    read: true,
    createdAt: "1 день назад",
    href: "/applications/2",
  },
  {
    id: "8",
    title: "Обновление системы",
    message: "Запланировано обновление системы на 20.01.2024",
    type: "info",
    read: true,
    createdAt: "2 дня назад",
    href: "/",
  },
]

