import type { Competition } from "@/types/competition"

export const mockCompetitions: Competition[] = [
  {
    id: "001",
    name: "Первенство России U-18",
    discipline: "Футбол",
    startDate: "15.01.2024",
    endDate: "15.01.2025",
    status: "ongoing",
    organizer: "Федерация легкой атлетики России",
    inMinistryList: false,
    participants: [
      { id: "p1", fullName: "Смирнов Алексей Владимирович", initials: "СА", status: "accepted" },
      { id: "p2", fullName: "Лебедев Павел Алексеевич", initials: "ЛП", status: "rejected" },
      { id: "p3", fullName: "Волкова Ольга Ивановна", initials: "ВО", status: "accepted" },
      { id: "p4", fullName: "Морозов Сергей Владимирович", initials: "МС", status: "accepted" },
      { id: "p5", fullName: "Соколов Андрей Николаевич", initials: "СА", status: "pending" },
      { id: "p6", fullName: "Петрова Елена Сергеевна", initials: "ПЕ", status: "accepted" },
      { id: "p7", fullName: "Васильев Дмитрий Юрьевич", initials: "ВД", status: "accepted" },
      { id: "p8", fullName: "Смирнова Мария Андреевна", initials: "СМ", status: "accepted" },
      { id: "p9", fullName: "Кузнецов Иван Петрович", initials: "КИ", status: "accepted" },
      { id: "p10", fullName: "Белов Михаил Иванович", initials: "БМ", status: "accepted" },
      { id: "p11", fullName: "Новиков Артем Сергеевич", initials: "НА", status: "accepted" },
      { id: "p12", fullName: "Федорова Анна Дмитриевна", initials: "ФА", status: "pending" },
      { id: "p13", fullName: "Иванов Роман Викторович", initials: "ИР", status: "accepted" },
      { id: "p14", fullName: "Попова Дарья Александровна", initials: "ПД", status: "accepted" },
      { id: "p15", fullName: "Соколов Максим Олегович", initials: "СМ", status: "rejected" },
      { id: "p16", fullName: "Лебедева Татьяна Игоревна", initials: "ЛТ", status: "accepted" },
      { id: "p17", fullName: "Козлов Владислав Андреевич", initials: "КВ", status: "accepted" },
      { id: "p18", fullName: "Орлова Екатерина Сергеевна", initials: "ОЕ", status: "pending" },
      { id: "p19", fullName: "Морозов Никита Дмитриевич", initials: "МН", status: "accepted" },
      { id: "p20", fullName: "Волков Станислав Петрович", initials: "ВС", status: "accepted" },
    ],
    judges: [
      { id: "j1", fullName: "Смирнов Алексей Владимирович", initials: "СА" },
      { id: "j2", fullName: "Лебедев Павел Алексеевич", initials: "ЛП" },
    ],
  },
  {
    id: "002",
    name: "Чемпионат России по легкой атлетике 2025",
    discipline: "Бег на 100 метров",
    startDate: "15.12.2025",
    endDate: "25.12.2025",
    status: "ongoing",
    organizer: "Федерация легкой атлетики России",
    inMinistryList: false,
    participants: [
      { id: "p1", fullName: "Смирнов Алексей Владимирович", initials: "СА", status: "accepted" },
      { id: "p2", fullName: "Лебедев Павел Алексеевич", initials: "ЛП", status: "rejected" },
      { id: "p3", fullName: "Волкова Ольга Ивановна", initials: "ВО", status: "accepted" },
      { id: "p4", fullName: "Морозов Сергей Владимирович", initials: "МС", status: "accepted" },
      { id: "p5", fullName: "Соколов Андрей Николаевич", initials: "СА", status: "pending" },
      { id: "p6", fullName: "Петрова Елена Сергеевна", initials: "ПЕ", status: "accepted" },
      { id: "p7", fullName: "Васильев Дмитрий Юрьевич", initials: "ВД", status: "accepted" },
      { id: "p8", fullName: "Смирнова Мария Андреевна", initials: "СМ", status: "accepted" },
      { id: "p9", fullName: "Кузнецов Иван Петрович", initials: "КИ", status: "accepted" },
      { id: "p10", fullName: "Белов Михаил Иванович", initials: "БМ", status: "accepted" },
    ],
    judges: [
      { id: "j1", fullName: "Смирнов Алексей Владимирович", initials: "СА" },
      { id: "j2", fullName: "Лебедев Павел Алексеевич", initials: "ЛП" },
    ],
  },
  {
    id: "003",
    name: "Кубок Москвы",
    discipline: "Вольный стиль",
    startDate: "08.06.2025",
    endDate: "08.06.2025",
    status: "planned",
  },
  {
    id: "004",
    name: "ЧР по Dota 2",
    discipline: "Многопользовательская онлайн-игра",
    startDate: "14.09.2025",
    endDate: "14.09.2026",
    status: "planned",
  },
  {
    id: "005",
    name: "Турнир Ботвинника",
    discipline: "Шахматы",
    startDate: "17.07.2025",
    endDate: "17.07.2025",
    status: "planned",
  },
  {
    id: "006",
    name: "Первенство СПб баскетбол",
    discipline: "Баскетбол",
    startDate: "01.01.2025",
    endDate: "01.01.2025",
    status: "planned",
  },
  {
    id: "007",
    name: "ВС по дзюдо",
    discipline: "Дзюдо",
    startDate: "29.02.2025",
    endDate: "29.02.2025",
    status: "planned",
  },
  {
    id: "008",
    name: "ЧР по Dota 2",
    discipline: "Многопользовательская онлайн-игра",
    startDate: "05.12.2024",
    endDate: "05.12.2024",
    status: "planned",
  },
  {
    id: "009",
    name: "ЧР по легкой атлетике",
    discipline: "Баскетбол",
    startDate: "11.03.2025",
    endDate: "11.03.2025",
    status: "planned",
  },
  {
    id: "010",
    name: "Первенство России U-18",
    discipline: "Футбол",
    startDate: "22.08.2026",
    endDate: "22.08.2026",
    status: "ongoing",
  },
  {
    id: "011",
    name: "Чемпионат России по плаванию",
    discipline: "Плавание",
    startDate: "10.03.2024",
    endDate: "15.03.2024",
    status: "completed",
  },
  {
    id: "012",
    name: "Кубок Европы по теннису",
    discipline: "Теннис",
    startDate: "20.05.2024",
    endDate: "25.05.2024",
    status: "completed",
  },
  {
    id: "013",
    name: "Первенство мира по гимнастике",
    discipline: "Гимнастика",
    startDate: "01.09.2025",
    endDate: "10.09.2025",
    status: "planned",
  },
  {
    id: "014",
    name: "Чемпионат России по хоккею",
    discipline: "Хоккей",
    startDate: "15.12.2023",
    endDate: "20.12.2023",
    status: "completed",
  },
  {
    id: "015",
    name: "Кубок России по волейболу",
    discipline: "Волейбол",
    startDate: "05.04.2024",
    endDate: "12.04.2024",
    status: "completed",
  },
  {
    id: "016",
    name: "Первенство России по боксу",
    discipline: "Бокс",
    startDate: "18.07.2025",
    endDate: "25.07.2025",
    status: "planned",
  },
  {
    id: "017",
    name: "Чемпионат Европы по легкой атлетике",
    discipline: "Бег на 100 метров",
    startDate: "12.06.2024",
    endDate: "18.06.2024",
    status: "completed",
  },
  {
    id: "018",
    name: "Кубок мира по футболу U-20",
    discipline: "Футбол",
    startDate: "01.08.2025",
    endDate: "15.08.2025",
    status: "planned",
  },
  {
    id: "019",
    name: "Первенство России по плаванию",
    discipline: "Вольный стиль",
    startDate: "20.02.2024",
    endDate: "25.02.2024",
    status: "completed",
  },
  {
    id: "020",
    name: "Чемпионат России по шахматам",
    discipline: "Шахматы",
    startDate: "10.11.2024",
    endDate: "20.11.2024",
    status: "completed",
  },
  {
    id: "021",
    name: "Кубок России по баскетболу",
    discipline: "Баскетбол",
    startDate: "15.03.2025",
    endDate: "22.03.2025",
    status: "planned",
  },
  {
    id: "022",
    name: "Первенство Европы по дзюдо",
    discipline: "Дзюдо",
    startDate: "05.05.2024",
    endDate: "10.05.2024",
    status: "completed",
  },
  {
    id: "023",
    name: "Чемпионат мира по киберспорту",
    discipline: "Многопользовательская онлайн-игра",
    startDate: "01.12.2025",
    endDate: "15.12.2025",
    status: "planned",
  },
  {
    id: "024",
    name: "Кубок России по гимнастике",
    discipline: "Гимнастика",
    startDate: "25.04.2024",
    endDate: "30.04.2024",
    status: "completed",
  },
  {
    id: "025",
    name: "Первенство России по теннису",
    discipline: "Теннис",
    startDate: "08.09.2025",
    endDate: "15.09.2025",
    status: "planned",
  },
  {
    id: "026",
    name: "Чемпионат России по хоккею U-18",
    discipline: "Хоккей",
    startDate: "20.01.2024",
    endDate: "28.01.2024",
    status: "completed",
  },
  {
    id: "027",
    name: "Кубок Европы по волейболу",
    discipline: "Волейбол",
    startDate: "10.07.2025",
    endDate: "18.07.2025",
    status: "planned",
  },
  {
    id: "028",
    name: "Первенство мира по боксу",
    discipline: "Бокс",
    startDate: "15.10.2024",
    endDate: "25.10.2024",
    status: "completed",
  },
  {
    id: "029",
    name: "Чемпионат России по плаванию",
    discipline: "Плавание",
    startDate: "05.06.2025",
    endDate: "12.06.2025",
    status: "planned",
  },
  {
    id: "030",
    name: "Кубок России по легкой атлетике",
    discipline: "Бег на 100 метров",
    startDate: "18.08.2024",
    endDate: "25.08.2024",
    status: "completed",
  },
]

export const filterOptions = {
  disciplines: [
    "Футбол",
    "Бег на 100 метров",
    "Вольный стиль",
    "Многопользовательская онлайн-игра",
    "Шахматы",
    "Баскетбол",
    "Дзюдо",
    "Плавание",
    "Теннис",
    "Хоккей",
    "Волейбол",
    "Бокс",
    "Гимнастика",
    "Легкая атлетика",
  ],
  statuses: [
    { value: "ongoing", label: "Уже идет" },
    { value: "completed", label: "Завершено" },
    { value: "planned", label: "Запланировано" },
  ],
}

export function getCompetitionCounts() {
  const counts = {
    disciplines: {} as Record<string, number>,
    statuses: {} as Record<string, number>,
  }

  mockCompetitions.forEach((comp) => {
    // Дисциплины
    counts.disciplines[comp.discipline] = (counts.disciplines[comp.discipline] || 0) + 1

    // Статусы
    counts.statuses[comp.status] = (counts.statuses[comp.status] || 0) + 1
  })

  return counts
}

