import type { Document } from "@/types/document"

export const mockDocuments: Document[] = [
  {
    id: "1",
    name: "Согласие на обработку персональных данных",
    type: "Согласие",
    status: "signed",
    date: "15 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "ПА", fullName: "Петрова Анна Сергеевна" },
    competition: "Чемпионат России 2024",
    discipline: "Футбол",
  },
  {
    id: "2",
    name: "Договор на участие",
    type: "Договор",
    status: "signed",
    date: "15 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "МС", fullName: "Морозов Сергей Александрович" },
    competition: "Чемпионат России 2024",
    discipline: "Хоккей",
  },
  {
    id: "3",
    name: "Медицинская справка",
    type: "Страховка",
    status: "signed",
    date: "15 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "МС", fullName: "Морозов Сергей Александрович" },
    competition: "Чемпионат России 2024",
    discipline: "Волейбол",
  },
  {
    id: "4",
    name: "Согласие на обработку персональных данных",
    type: "Согласие",
    status: "signed",
    date: "15 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "ПА", fullName: "Петрова Анна Сергеевна" },
    competition: "Чемпионат России 2024",
    discipline: "Бокс",
  },
  {
    id: "5",
    name: "Согласие на обработку персональных данных",
    type: "Согласие",
    status: "signed",
    date: "15 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "ПА", fullName: "Петрова Анна Сергеевна" },
    competition: "Чемпионат России 2024",
    discipline: "Плавание",
  },
  {
    id: "6",
    name: "Согласие на обработку персональных данных",
    type: "Согласие",
    status: "unsigned",
    size: "1.20 МБ",
    athlete: { initials: "ПА", fullName: "Петрова Анна Сергеевна" },
    competition: "Чемпионат России 2024",
    discipline: "Баскетбол",
  },
  {
    id: "7",
    name: "Согласие на обработку персональных данных",
    type: "Согласие",
    status: "unsigned",
    size: "1.20 МБ",
    athlete: { initials: "ПА", fullName: "Петрова Анна Сергеевна" },
    competition: "Чемпионат России 2024",
    discipline: "Футбол",
  },
  {
    id: "8",
    name: "Согласие на обработку персональных данных",
    type: "Согласие",
    status: "unsigned",
    size: "1.20 МБ",
    athlete: { initials: "ПА", fullName: "Петрова Анна Сергеевна" },
    competition: "Чемпионат России 2024",
    discipline: "Гимнастика",
  },
  {
    id: "9",
    name: "Согласие на обработку персональных данных",
    type: "Согласие",
    status: "unsigned",
    size: "1.20 МБ",
    athlete: { initials: "ПА", fullName: "Петрова Анна Сергеевна" },
    competition: "Чемпионат России 2024",
    discipline: "Легкая атлетика",
  },
  {
    id: "10",
    name: "Согласие на обработку персональных данных",
    type: "Согласие",
    status: "unsigned",
    size: "1.20 МБ",
    athlete: { initials: "ПА", fullName: "Петрова Анна Сергеевна" },
    competition: "Чемпионат России 2024",
    discipline: "Теннис",
  },
  {
    id: "11",
    name: "Договор на участие",
    type: "Договор",
    status: "signed",
    date: "15 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "СА", fullName: "Сидоров Алексей Николаевич" },
    competition: "Чемпионат России 2024",
    discipline: "Футбол",
  },
  {
    id: "12",
    name: "Договор на участие",
    type: "Договор",
    status: "signed",
    date: "15 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "СА", fullName: "Сидоров Алексей Николаевич" },
    competition: "Чемпионат России 2024",
    discipline: "Хоккей",
  },
  {
    id: "13",
    name: "Договор на участие",
    type: "Договор",
    status: "signed",
    date: "15 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "СА", fullName: "Сидоров Алексей Николаевич" },
    competition: "Чемпионат России 2024",
    discipline: "Волейбол",
  },
  {
    id: "14",
    name: "Договор на участие",
    type: "Договор",
    status: "signed",
    date: "15 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "СА", fullName: "Сидоров Алексей Николаевич" },
    competition: "Чемпионат России 2024",
    discipline: "Бокс",
  },
  {
    id: "15",
    name: "Медицинская справка",
    type: "Страховка",
    status: "signed",
    date: "15 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "КМ", fullName: "Кузнецова Мария Владимировна" },
    competition: "Чемпионат России 2024",
    discipline: "Плавание",
  },
  {
    id: "16",
    name: "Медицинская справка",
    type: "Страховка",
    status: "signed",
    date: "15 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "КМ", fullName: "Кузнецова Мария Владимировна" },
    competition: "Чемпионат России 2024",
    discipline: "Гимнастика",
  },
  {
    id: "17",
    name: "Согласие на обработку персональных данных",
    type: "Согласие",
    status: "unsigned",
    size: "1.20 МБ",
    athlete: { initials: "СД", fullName: "Смирнов Дмитрий Павлович" },
    competition: "Чемпионат России 2024",
    discipline: "Легкая атлетика",
  },
  {
    id: "18",
    name: "Договор на участие",
    type: "Договор",
    status: "signed",
    date: "15 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "ФО", fullName: "Федорова Ольга Игоревна" },
    competition: "Чемпионат России 2024",
    discipline: "Теннис",
  },
  {
    id: "19",
    name: "Медицинская справка",
    type: "Страховка",
    status: "signed",
    date: "15 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "ФО", fullName: "Федорова Ольга Игоревна" },
    competition: "Чемпионат России 2024",
    discipline: "Баскетбол",
  },
  {
    id: "20",
    name: "Согласие на обработку персональных данных",
    type: "Согласие",
    status: "signed",
    date: "15 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "ФО", fullName: "Федорова Ольга Игоревна" },
    competition: "Чемпионат России 2024",
    discipline: "Волейбол",
  },
  {
    id: "21",
    name: "Договор на участие",
    type: "Договор",
    status: "signed",
    date: "15 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "ФО", fullName: "Федорова Ольга Игоревна" },
    competition: "Чемпионат России 2024",
    discipline: "Футбол",
  },
  {
    id: "22",
    name: "Согласие на обработку персональных данных",
    type: "Согласие",
    status: "signed",
    date: "15 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "ФО", fullName: "Федорова Ольга Игоревна" },
    competition: "Чемпионат России 2024",
    discipline: "Хоккей",
  },
  {
    id: "23",
    name: "Медицинская справка",
    type: "Страховка",
    status: "signed",
    date: "15 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "ФО", fullName: "Федорова Ольга Игоревна" },
    competition: "Чемпионат России 2024",
    discipline: "Бокс",
  },
  {
    id: "24",
    name: "Договор на участие",
    type: "Договор",
    status: "unsigned",
    size: "1.20 МБ",
    athlete: { initials: "ЛЕ", fullName: "Лебедева Екатерина Викторовна" },
    competition: "Чемпионат России 2024",
    discipline: "Плавание",
  },
  {
    id: "25",
    name: "Согласие на обработку персональных данных",
    type: "Согласие",
    status: "signed",
    date: "15 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "ИИ", fullName: "Иванов Иван Иванович" },
    competition: "Чемпионат России 2024",
    discipline: "Футбол",
  },
  {
    id: "26",
    name: "Договор на участие",
    type: "Договор",
    status: "signed",
    date: "15 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "ИИ", fullName: "Иванов Иван Иванович" },
    competition: "Чемпионат России 2024",
    discipline: "Хоккей",
  },
  {
    id: "27",
    name: "Медицинская справка",
    type: "Страховка",
    status: "signed",
    date: "15 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "ИР", fullName: "Иванчук Роман Александрович" },
    competition: "Чемпионат России 2024",
    discipline: "Бокс",
  },
  {
    id: "28",
    name: "Согласие на обработку персональных данных",
    type: "Согласие",
    status: "unsigned",
    size: "1.20 МБ",
    athlete: { initials: "СИ", fullName: "Смирнов Иван Владимирович" },
    competition: "Чемпионат России 2024",
    discipline: "Теннис",
  },
  {
    id: "29",
    name: "Договор на участие",
    type: "Договор",
    status: "signed",
    date: "20 янв. 2025",
    size: "1.50 МБ",
    athlete: { initials: "ВП", fullName: "Волков Павел Сергеевич" },
    competition: "Кубок России 2024",
    discipline: "Футбол",
  },
  {
    id: "30",
    name: "Медицинская справка",
    type: "Страховка",
    status: "signed",
    date: "18 янв. 2025",
    size: "0.95 МБ",
    athlete: { initials: "НК", fullName: "Новикова Ксения Андреевна" },
    competition: "Кубок России 2024",
    discipline: "Гимнастика",
  },
  {
    id: "31",
    name: "Договор на участие",
    type: "Договор",
    status: "unsigned",
    size: "1.30 МБ",
    athlete: { initials: "РМ", fullName: "Романов Максим Дмитриевич" },
    competition: "Чемпионат Европы 2024",
    discipline: "Хоккей",
  },
  {
    id: "32",
    name: "Согласие на обработку персональных данных",
    type: "Согласие",
    status: "signed",
    date: "22 янв. 2025",
    size: "1.10 МБ",
    athlete: { initials: "ЗА", fullName: "Захарова Анастасия Викторовна" },
    competition: "Чемпионат Европы 2024",
    discipline: "Плавание",
  },
  {
    id: "33",
    name: "Медицинская справка",
    type: "Страховка",
    status: "signed",
    date: "19 янв. 2025",
    size: "1.25 МБ",
    athlete: { initials: "ОС", fullName: "Орлов Станислав Игоревич" },
    competition: "Кубок России 2024",
    discipline: "Бокс",
  },
  {
    id: "34",
    name: "Договор на участие",
    type: "Договор",
    status: "signed",
    date: "21 янв. 2025",
    size: "1.40 МБ",
    athlete: { initials: "ТЕ", fullName: "Титова Елена Петровна" },
    competition: "Чемпионат мира 2024",
    discipline: "Теннис",
  },
  {
    id: "35",
    name: "Согласие на обработку персональных данных",
    type: "Согласие",
    status: "unsigned",
    size: "1.15 МБ",
    athlete: { initials: "БД", fullName: "Белов Денис Олегович" },
    competition: "Чемпионат мира 2024",
    discipline: "Баскетбол",
  },
  {
    id: "36",
    name: "Медицинская справка",
    type: "Страховка",
    status: "signed",
    date: "17 янв. 2025",
    size: "1.05 МБ",
    athlete: { initials: "ГМ", fullName: "Григорьева Марина Александровна" },
    competition: "Кубок России 2024",
    discipline: "Волейбол",
  },
  {
    id: "37",
    name: "Договор на участие",
    type: "Договор",
    status: "signed",
    date: "23 янв. 2025",
    size: "1.35 МБ",
    athlete: { initials: "КВ", fullName: "Козлов Владимир Николаевич" },
    competition: "Чемпионат Европы 2024",
    discipline: "Легкая атлетика",
  },
  {
    id: "38",
    name: "Согласие на обработку персональных данных",
    type: "Согласие",
    status: "signed",
    date: "16 янв. 2025",
    size: "1.20 МБ",
    athlete: { initials: "СВ", fullName: "Соколова Виктория Сергеевна" },
    competition: "Чемпионат мира 2024",
    discipline: "Гимнастика",
  },
  {
    id: "39",
    name: "Медицинская справка",
    type: "Страховка",
    status: "unsigned",
    size: "0.90 МБ",
    athlete: { initials: "МА", fullName: "Медведев Артем Юрьевич" },
    competition: "Кубок России 2024",
    discipline: "Футбол",
  },
  {
    id: "40",
    name: "Договор на участие",
    type: "Договор",
    status: "signed",
    date: "24 янв. 2025",
    size: "1.45 МБ",
    athlete: { initials: "ПО", fullName: "Попова Оксана Дмитриевна" },
    competition: "Чемпионат Европы 2024",
    discipline: "Плавание",
  },
  {
    id: "41",
    name: "Согласие на обработку персональных данных",
    type: "Согласие",
    status: "signed",
    date: "25 янв. 2025",
    size: "1.18 МБ",
    athlete: { initials: "ЛВ", fullName: "Лазарев Вадим Романович" },
    competition: "Чемпионат мира 2024",
    discipline: "Хоккей",
  },
  {
    id: "42",
    name: "Медицинская справка",
    type: "Страховка",
    status: "signed",
    date: "26 янв. 2025",
    size: "1.12 МБ",
    athlete: { initials: "ЯИ", fullName: "Яковлева Ирина Алексеевна" },
    competition: "Кубок России 2024",
    discipline: "Теннис",
  },
  {
    id: "43",
    name: "Договор на участие",
    type: "Договор",
    status: "unsigned",
    size: "1.28 МБ",
    athlete: { initials: "ФИ", fullName: "Фомин Игорь Владимирович" },
    competition: "Чемпионат Европы 2024",
    discipline: "Бокс",
  },
  {
    id: "44",
    name: "Согласие на обработку персональных данных",
    type: "Согласие",
    status: "signed",
    date: "27 янв. 2025",
    size: "1.22 МБ",
    athlete: { initials: "ДЮ", fullName: "Данилова Юлия Павловна" },
    competition: "Чемпионат мира 2024",
    discipline: "Волейбол",
  },
  {
    id: "45",
    name: "Медицинская справка",
    type: "Страховка",
    status: "signed",
    date: "28 янв. 2025",
    size: "1.08 МБ",
    athlete: { initials: "АС", fullName: "Антонов Сергей Борисович" },
    competition: "Кубок России 2024",
    discipline: "Баскетбол",
  },
  {
    id: "46",
    name: "Договор на участие",
    type: "Договор",
    status: "signed",
    date: "29 янв. 2025",
    size: "1.38 МБ",
    athlete: { initials: "ТМ", fullName: "Тарасова Мария Игоревна" },
    competition: "Чемпионат Европы 2024",
    discipline: "Легкая атлетика",
  },
  {
    id: "47",
    name: "Согласие на обработку персональных данных",
    type: "Согласие",
    status: "unsigned",
    size: "1.16 МБ",
    athlete: { initials: "ША", fullName: "Широков Андрей Константинович" },
    competition: "Чемпионат мира 2024",
    discipline: "Гимнастика",
  },
  {
    id: "48",
    name: "Медицинская справка",
    type: "Страховка",
    status: "signed",
    date: "30 янв. 2025",
    size: "1.14 МБ",
    athlete: { initials: "БЕ", fullName: "Борисова Елена Викторовна" },
    competition: "Кубок России 2024",
    discipline: "Футбол",
  },
  {
    id: "49",
    name: "Договор на участие",
    type: "Договор",
    status: "signed",
    date: "31 янв. 2025",
    size: "1.42 МБ",
    athlete: { initials: "МИ", fullName: "Михайлов Илья Сергеевич" },
    competition: "Чемпионат Европы 2024",
    discipline: "Плавание",
  },
  {
    id: "50",
    name: "Согласие на обработку персональных данных",
    type: "Согласие",
    status: "signed",
    date: "1 фев. 2025",
    size: "1.19 МБ",
    athlete: { initials: "КН", fullName: "Королева Наталья Дмитриевна" },
    competition: "Чемпионат мира 2024",
    discipline: "Хоккей",
  },
]

export const filterOptions = {
  athletes: [
    "Петрова Анна Сергеевна",
    "Сидоров Алексей Николаевич",
    "Кузнецова Мария Владимировна",
    "Смирнов Дмитрий Павлович",
    "Федорова Ольга Игоревна",
    "Морозов Сергей Александрович",
    "Лебедева Екатерина Викторовна",
    "Иванов Иван Иванович",
    "Иванчук Роман Александрович",
    "Смирнов Иван Владимирович",
    "Волков Павел Сергеевич",
    "Новикова Ксения Андреевна",
    "Романов Максим Дмитриевич",
    "Захарова Анастасия Викторовна",
    "Орлов Станислав Игоревич",
    "Титова Елена Петровна",
    "Белов Денис Олегович",
    "Григорьева Марина Александровна",
    "Козлов Владимир Николаевич",
    "Соколова Виктория Сергеевна",
    "Медведев Артем Юрьевич",
    "Попова Оксана Дмитриевна",
    "Лазарев Вадим Романович",
    "Яковлева Ирина Алексеевна",
    "Фомин Игорь Владимирович",
    "Данилова Юлия Павловна",
    "Антонов Сергей Борисович",
    "Тарасова Мария Игоревна",
    "Широков Андрей Константинович",
    "Борисова Елена Викторовна",
    "Михайлов Илья Сергеевич",
    "Королева Наталья Дмитриевна",
  ],
  competitions: [
    "Чемпионат России 2024",
    "Чемпионат России 2024 по футболу",
    "Кубок России 2024",
    "Чемпионат Европы 2024",
    "Чемпионат мира 2024",
  ],
  disciplines: [
    "Футбол",
    "Хоккей",
    "Волейбол",
    "Бокс",
    "Плавание",
    "Баскетбол",
    "Гимнастика",
    "Легкая атлетика",
    "Теннис",
  ],
  statuses: [
    { value: "signed", label: "Подписан" },
    { value: "unsigned", label: "Не подписан" },
  ],
  documentTypes: ["Согласие", "Договор", "Страховка"],
}

export function getDocumentCounts() {
  const counts = {
    athletes: {} as Record<string, number>,
    competitions: {} as Record<string, number>,
    disciplines: {} as Record<string, number>,
    statuses: {} as Record<string, number>,
    documentTypes: {} as Record<string, number>,
  }

  mockDocuments.forEach((doc) => {
    // Спортсмены
    const athleteName = doc.athlete.fullName
    counts.athletes[athleteName] = (counts.athletes[athleteName] || 0) + 1

    // Соревнования
    counts.competitions[doc.competition] = (counts.competitions[doc.competition] || 0) + 1

    // Дисциплины
    counts.disciplines[doc.discipline] = (counts.disciplines[doc.discipline] || 0) + 1

    // Статусы
    counts.statuses[doc.status] = (counts.statuses[doc.status] || 0) + 1

    // Типы документов
    counts.documentTypes[doc.type] = (counts.documentTypes[doc.type] || 0) + 1
  })

  return counts
}
