import type { Application } from "@/types/application"

export const mockApplications: Application[] = [
  {
    id: "1",
    applicationId: "2025001",
    athlete: {
      initials: "ПА",
      fullName: "Петрова Анна Сергеевна",
      email: "petrova@example.com",
      phone: "+7 (999) 123-45-67",
      birthDate: "11 мая 2001",
      age: 24,
    },
    competition: {
      name: "Чемпионат России 2024",
      dateRange: "10 фев. - 16 фев. 2025",
      discipline: "Футбол",
      participants: 156,
      location: "Москва, СК Олимпийский",
    },
    submissionDate: "12 янв. 2025",
    status: "accepted",
    documents: [
      {
        id: "doc1",
        name: "Соглашение об участии в соревновании",
        type: "Согласие",
        status: "signed",
        date: "15 янв. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc2",
        name: "Антидопинговая декларация",
        type: "Договор",
        status: "signed",
        date: "15 янв. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc3",
        name: "Этическая декларация",
        type: "Страховка",
        status: "signed",
        date: "15 янв. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc4",
        name: "Соглашение о неразглашении (NDA)",
        type: "Согласие",
        status: "signed",
        date: "15 янв. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc5",
        name: "Соглашение о неразглашении (NDA)",
        type: "Согласие",
        status: "unsigned",
        size: "1.20 МБ",
      },
    ],
  },
  {
    id: "2",
    applicationId: "2025002",
    athlete: {
      initials: "ПА",
      fullName: "Петрова Анна Сергеевна",
      email: "petrova@example.com",
      phone: "+7 (999) 123-45-67",
      birthDate: "11 мая 2001",
      age: 24,
    },
    competition: {
      name: "Летние игры России 2024",
      dateRange: "5 мар. - 11 мар. 2025",
      discipline: "Киберспорт Dota 2",
      participants: 128,
      location: "Санкт-Петербург, Ледовый дворец",
    },
    submissionDate: "22 фев. 2025",
    status: "pending",
    documents: [
      {
        id: "doc6",
        name: "Соглашение об участии в соревновании",
        type: "Согласие",
        status: "signed",
        date: "23 фев. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc7",
        name: "Антидопинговая декларация",
        type: "Договор",
        status: "unsigned",
        date: "23 фев. 2025",
        size: "1.20 МБ",
      },
    ],
  },
  {
    id: "3",
    applicationId: "2025003",
    athlete: {
      initials: "ПА",
      fullName: "Петрова Анна Сергеевна",
      email: "petrova@example.com",
      phone: "+7 (999) 123-45-67",
      birthDate: "11 мая 2001",
      age: 24,
    },
    competition: {
      name: "Чемпионат по плаванию России 2024",
      dateRange: "1 нояб. - 7 нояб. 2025",
      discipline: "Плавание",
      participants: 89,
      location: "Казань, Дворец водных видов спорта",
    },
    submissionDate: "16 окт. 2025",
    status: "rejected",
    documents: [
      {
        id: "doc8",
        name: "Соглашение об участии в соревновании",
        type: "Согласие",
        status: "signed",
        date: "17 окт. 2025",
        size: "1.15 МБ",
      },
      {
        id: "doc9",
        name: "Медицинская справка",
        type: "Договор",
        status: "signed",
        date: "17 окт. 2025",
        size: "0.85 МБ",
      },
    ],
  },
  {
    id: "4",
    applicationId: "2025004",
    athlete: {
      initials: "ПА",
      fullName: "Петрова Анна Сергеевна",
      email: "petrova@example.com",
      phone: "+7 (999) 123-45-67",
      birthDate: "11 мая 2001",
      age: 24,
    },
    competition: {
      name: "Турнир по баскетболу России 2024",
      dateRange: "2 июл. - 8 июл. 2025",
      discipline: "Баскетбол",
      participants: 144,
      location: "Москва, УСК ЦСКА",
    },
    submissionDate: "6 апр. 2025",
    status: "accepted",
    documents: [
      {
        id: "doc10",
        name: "Соглашение об участии в соревновании",
        type: "Согласие",
        status: "signed",
        date: "7 апр. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc11",
        name: "Антидопинговая декларация",
        type: "Договор",
        status: "signed",
        date: "7 апр. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc12",
        name: "Этическая декларация",
        type: "Страховка",
        status: "signed",
        date: "7 апр. 2025",
        size: "1.20 МБ",
      },
    ],
  },
  {
    id: "5",
    applicationId: "2025005",
    athlete: {
      initials: "ПА",
      fullName: "Петрова Анна Сергеевна",
      email: "petrova@example.com",
      phone: "+7 (999) 123-45-67",
      birthDate: "11 мая 2001",
      age: 24,
    },
    competition: {
      name: "Чемпионат по волейболу России 2024",
      dateRange: "8 июн. - 14 июн. 2025",
      discipline: "Волейбол",
      participants: 120,
      location: "Краснодар, Дворец спорта Олимп",
    },
    submissionDate: "2 мая 2025",
    status: "accepted",
    documents: [
      {
        id: "doc13",
        name: "Соглашение об участии в соревновании",
        type: "Согласие",
        status: "signed",
        date: "3 мая 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc14",
        name: "Антидопинговая декларация",
        type: "Договор",
        status: "signed",
        date: "3 мая 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc15",
        name: "Этическая декларация",
        type: "Страховка",
        status: "signed",
        date: "3 мая 2025",
        size: "1.20 МБ",
      },
    ],
  },
  {
    id: "6",
    applicationId: "2025006",
    athlete: {
      initials: "ПА",
      fullName: "Петрова Анна Сергеевна",
      email: "petrova@example.com",
      phone: "+7 (999) 123-45-67",
      birthDate: "11 мая 2001",
      age: 24,
    },
    competition: {
      name: "Кубок России по футболу 2024",
      dateRange: "15 мая - 21 мая 2025",
      discipline: "Футбол",
      participants: 256,
      location: "Санкт-Петербург, Газпром Арена",
    },
    submissionDate: "26 июл. 2025",
    status: "accepted",
    documents: [
      {
        id: "doc16",
        name: "Соглашение об участии в соревновании",
        type: "Согласие",
        status: "signed",
        date: "27 июл. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc17",
        name: "Антидопинговая декларация",
        type: "Договор",
        status: "signed",
        date: "27 июл. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc18",
        name: "Этическая декларация",
        type: "Страховка",
        status: "signed",
        date: "27 июл. 2025",
        size: "1.20 МБ",
      },
    ],
  },
  {
    id: "7",
    applicationId: "2025007",
    athlete: {
      initials: "МС",
      fullName: "Морозов Сергей Александрович",
      email: "morozov.sergey@example.com",
      phone: "+7 (999) 234-56-78",
      birthDate: "15 мар. 1999",
      age: 26,
    },
    competition: {
      name: "Зимний чемпионат России 2024",
      dateRange: "20 апр. - 26 апр. 2025",
      discipline: "Лыжные гонки",
      participants: 112,
      location: "Сочи, Лыжный комплекс Лаура",
    },
    submissionDate: "6 сен. 2025",
    status: "accepted",
    documents: [
      {
        id: "doc19",
        name: "Соглашение об участии в соревновании",
        type: "Согласие",
        status: "signed",
        date: "7 сен. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc20",
        name: "Антидопинговая декларация",
        type: "Договор",
        status: "signed",
        date: "7 сен. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc21",
        name: "Этическая декларация",
        type: "Страховка",
        status: "signed",
        date: "7 сен. 2025",
        size: "1.20 МБ",
      },
    ],
  },
  {
    id: "8",
    applicationId: "2025008",
    athlete: {
      initials: "МС",
      fullName: "Морозов Сергей Александрович",
      email: "morozov.sergey@example.com",
      phone: "+7 (999) 234-56-78",
      birthDate: "15 мар. 1999",
      age: 26,
    },
    competition: {
      name: "Чемпионат по хоккею России 2024",
      dateRange: "10 сен. - 16 сен. 2025",
      discipline: "Хоккей",
      participants: 180,
      location: "Москва, ВТБ Арена",
    },
    submissionDate: "11 июн. 2025",
    status: "pending",
    documents: [
      {
        id: "doc22",
        name: "Соглашение об участии в соревновании",
        type: "Согласие",
        status: "unsigned",
        size: "1.20 МБ",
      },
      {
        id: "doc23",
        name: "Медицинская справка",
        type: "Договор",
        status: "unsigned",
        size: "0.85 МБ",
      },
    ],
  },
  {
    id: "9",
    applicationId: "2025009",
    athlete: {
      initials: "МС",
      fullName: "Морозов Сергей Александрович",
      email: "morozov.sergey@example.com",
      phone: "+7 (999) 234-56-78",
      birthDate: "15 мар. 1999",
      age: 26,
    },
    competition: {
      name: "Гран-при России по автоспорту 2024",
      dateRange: "5 окт. - 11 окт. 2025",
      discipline: "Автогонки",
      participants: 64,
      location: "Сочи, Автодром",
    },
    submissionDate: "14 янв. 2025",
    status: "accepted",
    documents: [
      {
        id: "doc24",
        name: "Соглашение об участии в соревновании",
        type: "Согласие",
        status: "signed",
        date: "15 янв. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc25",
        name: "Антидопинговая декларация",
        type: "Договор",
        status: "signed",
        date: "15 янв. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc26",
        name: "Этическая декларация",
        type: "Страховка",
        status: "signed",
        date: "15 янв. 2025",
        size: "1.20 МБ",
      },
    ],
  },
  {
    id: "10",
    applicationId: "2025010",
    athlete: {
      initials: "СА",
      fullName: "Сидоров Алексей Николаевич",
      email: "sidorov.alexey@example.com",
      phone: "+7 (999) 345-67-89",
      birthDate: "22 авг. 1997",
      age: 28,
    },
    competition: {
      name: "Чемпионат России 2024",
      dateRange: "10 фев. - 16 фев. 2025",
      discipline: "Футбол",
      participants: 256,
      location: "Москва, СК Олимпийский",
    },
    submissionDate: "15 янв. 2025",
    status: "accepted",
    documents: [
      {
        id: "doc27",
        name: "Соглашение об участии в соревновании",
        type: "Согласие",
        status: "signed",
        date: "16 янв. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc28",
        name: "Антидопинговая декларация",
        type: "Договор",
        status: "signed",
        date: "16 янв. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc29",
        name: "Этическая декларация",
        type: "Страховка",
        status: "signed",
        date: "16 янв. 2025",
        size: "1.20 МБ",
      },
    ],
  },
  {
    id: "11",
    applicationId: "2025011",
    athlete: {
      initials: "СА",
      fullName: "Сидоров Алексей Николаевич",
      email: "sidorov.alexey@example.com",
      phone: "+7 (999) 345-67-89",
      birthDate: "22 авг. 1997",
      age: 28,
    },
    competition: {
      name: "Соревнования по легкой атлетике России 2024",
      dateRange: "25 авг. - 31 авг. 2025",
      discipline: "Легкая атлетика",
      participants: 200,
      location: "Москва, Лужники",
    },
    submissionDate: "16 мар. 2025",
    status: "pending",
    documents: [
      {
        id: "doc30",
        name: "Соглашение об участии в соревновании",
        type: "Согласие",
        status: "unsigned",
        size: "1.20 МБ",
      },
      {
        id: "doc31",
        name: "Медицинская справка",
        type: "Договор",
        status: "unsigned",
        size: "0.85 МБ",
      },
    ],
  },
  {
    id: "12",
    applicationId: "2025012",
    athlete: {
      initials: "КМ",
      fullName: "Кузнецова Мария Владимировна",
      email: "kuznetsova.maria@example.com",
      phone: "+7 (999) 456-78-90",
      birthDate: "8 дек. 2000",
      age: 25,
    },
    competition: {
      name: "Чемпионат России 2024",
      dateRange: "10 фев. - 16 фев. 2025",
      discipline: "Футбол",
      participants: 256,
      location: "Москва, СК Олимпийский",
    },
    submissionDate: "13 янв. 2025",
    status: "accepted",
    documents: [
      {
        id: "doc32",
        name: "Соглашение об участии в соревновании",
        type: "Согласие",
        status: "signed",
        date: "14 янв. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc33",
        name: "Антидопинговая декларация",
        type: "Договор",
        status: "signed",
        date: "14 янв. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc34",
        name: "Этическая декларация",
        type: "Страховка",
        status: "signed",
        date: "14 янв. 2025",
        size: "1.20 МБ",
      },
    ],
  },
  {
    id: "13",
    applicationId: "2025013",
    athlete: {
      initials: "КМ",
      fullName: "Кузнецова Мария Владимировна",
      email: "kuznetsova.maria@example.com",
      phone: "+7 (999) 456-78-90",
      birthDate: "8 дек. 2000",
      age: 25,
    },
    competition: {
      name: "Летние игры России 2024",
      dateRange: "5 мар. - 11 мар. 2025",
      discipline: "Киберспорт Dota 2",
      participants: 128,
      location: "Санкт-Петербург, Ледовый дворец",
    },
    submissionDate: "20 фев. 2025",
    status: "rejected",
    documents: [
      {
        id: "doc35",
        name: "Соглашение об участии в соревновании",
        type: "Согласие",
        status: "signed",
        date: "21 фев. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc36",
        name: "Медицинская справка",
        type: "Договор",
        status: "signed",
        date: "21 фев. 2025",
        size: "0.85 МБ",
      },
    ],
  },
  {
    id: "14",
    applicationId: "2025014",
    athlete: {
      initials: "ФО",
      fullName: "Федорова Ольга Игоревна",
      email: "fedorova.olga@example.com",
      phone: "+7 (999) 567-89-01",
      birthDate: "3 июн. 1998",
      age: 27,
    },
    competition: {
      name: "Чемпионат России 2024",
      dateRange: "10 фев. - 16 фев. 2025",
      discipline: "Футбол",
      participants: 256,
      location: "Москва, СК Олимпийский",
    },
    submissionDate: "11 янв. 2025",
    status: "accepted",
    documents: [
      {
        id: "doc37",
        name: "Соглашение об участии в соревновании",
        type: "Согласие",
        status: "signed",
        date: "12 янв. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc38",
        name: "Антидопинговая декларация",
        type: "Договор",
        status: "signed",
        date: "12 янв. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc39",
        name: "Этическая декларация",
        type: "Страховка",
        status: "signed",
        date: "12 янв. 2025",
        size: "1.20 МБ",
      },
    ],
  },
  {
    id: "15",
    applicationId: "2025015",
    athlete: {
      initials: "ИИ",
      fullName: "Иванов Иван Иванович",
      email: "ivanov.ivan@example.com",
      phone: "+7 (999) 678-90-12",
      birthDate: "19 сен. 1996",
      age: 29,
    },
    competition: {
      name: "Кубок России по футболу 2024",
      dateRange: "15 мая - 21 мая 2025",
      discipline: "Футбол",
      participants: 256,
      location: "Санкт-Петербург, Газпром Арена",
    },
    submissionDate: "10 апр. 2025",
    status: "accepted",
    documents: [
      {
        id: "doc40",
        name: "Соглашение об участии в соревновании",
        type: "Согласие",
        status: "signed",
        date: "11 апр. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc41",
        name: "Антидопинговая декларация",
        type: "Договор",
        status: "signed",
        date: "11 апр. 2025",
        size: "1.20 МБ",
      },
      {
        id: "doc42",
        name: "Этическая декларация",
        type: "Страховка",
        status: "signed",
        date: "11 апр. 2025",
        size: "1.20 МБ",
      },
    ],
  },
]

export const applicationFilterOptions = {
  athletes: [
    "Петрова Анна Сергеевна",
    "Морозов Сергей Александрович",
    "Сидоров Алексей Николаевич",
    "Кузнецова Мария Владимировна",
    "Федорова Ольга Игоревна",
    "Иванов Иван Иванович",
  ],
  competitions: [
    "Чемпионат России 2024",
    "Зимний чемпионат России 2024",
    "Кубок России по футболу 2024",
    "Чемпионат по волейболу России 2024",
    "Турнир по баскетболу России 2024",
    "Соревнования по легкой атлетике России 2024",
    "Чемпионат по хоккею России 2024",
    "Гран-при России по автоспорту 2024",
    "Чемпионат по плаванию России 2024",
    "Летние игры России 2024",
  ],
  statuses: [
    { value: "accepted", label: "Принята" },
    { value: "pending", label: "На рассмотрении" },
    { value: "rejected", label: "Отклонена" },
  ],
}

export function getApplicationCounts() {
  const counts = {
    athletes: {} as Record<string, number>,
    competitions: {} as Record<string, number>,
    statuses: {} as Record<string, number>,
  }

  mockApplications.forEach((app) => {
    // Спортсмены
    const athleteName = app.athlete.fullName
    counts.athletes[athleteName] = (counts.athletes[athleteName] || 0) + 1

    // Соревнования
    counts.competitions[app.competition.name] = (counts.competitions[app.competition.name] || 0) + 1

    // Статусы
    counts.statuses[app.status] = (counts.statuses[app.status] || 0) + 1
  })

  return counts
}

